---
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformRepository
metadata:
  name: burrito-test-repo
  namespace: burrito-system
spec:
  repository:
    url: "https://github.com/rootleveltech/tf-demo.git"
    secretName: "github-creds"
  terraform:
    enabled: true

---
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformLayer
metadata:
  name: burrito-test-layer
  namespace: burrito-system
spec:
  repository:
    name: burrito-test-repo
    namespace: burrito-system
  path: "."
  branch: "v2.0.0"
  allowPrOnTags: true
  remediationStrategy:
    autoApply: false
