# Configuration File
# Generated by Terraform for Burrito Tag Support Testing

Project: ${project_name}
Environment: ${environment}
Generated: ${timestamp}

# This file demonstrates Burrito's ability to clone repositories
# using both branch and tag references for Terraform deployments.

---
Infrastructure Details:
- Provider: Local (for testing)
- Managed by: Burrito Kubernetes Operator
- Configuration Version: Using Git tags for versioning
